[package]
name = "rpcbinder"
version = "0.1.0"
edition = "2021"
description = "RPC Binder bindings for Android"
license = "Apache-2.0"

[dependencies]
binder_rpc_unstable_bindgen = { package = "binder_rpc_unstable_bindgen", version = "0.1", path = "./binder_rpc_unstable_bindgen" }
binder-ndk-sys = { package = "binder-ndk-sys", version = "0.1", path = "./../sys" }
binder = { package = "binder", version = "0.1", path = ".." }
foreign-types = "0.3.1"
cfg-if = "1.0.4"
log = "0.4.20"

[lib]
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.70.1"
